# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Super Giants Soccer Club</title>
</head>
<body>

    <!-- Header Section -->
    <header>
        <h1>Welcome to Super Giants Soccer Club</h1>
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#coaches">Coaches</a></li>
                <li><a href="#players">Players</a></li>
            </ul>
        </nav>
    </header>

    <!-- Home Page -->
    <section id="home">
        <h2>Welcome to Super Giants Soccer Club</h2>
        <p>Find out more about our coaches and players.</p>
    </section>

    <!-- Coaches Page -->
    <section id="coaches">
        <h2>Coaches</h2>
        <!-- Add coach information here -->
    </section>

    <!-- Players Page -->
    <section id="players">
        <h2>Players</h2>
        <!-- Add player information here -->
    </section>

    <!-- Footer Section -->
    <footer>
        <p>&copy; 2023 Super Giants Soccer Club</p>
    </footer>
</body>
</html>


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
